### ISSUE TITLE
Mobile: Home section: messages are invisible. 

### ISSUE THREAD

**Issue by rdok** [codeburrow/company-web-app#18]
Prio: Low

@PadawanTony Or is this the required behavior?

**Comment by PadawanTony** [comment]
@rdok You mean the titles on the carousel? Or the titles in the gallery section?

Both of these were designed as such from the template we got.

It would be nice to show them somehow (especially the gallery titles for every item) but it is not of high importance.

Note: The highest importance regarding our site is the loading speed which is slow.

**Comment by rdok** [comment]
@PadawanTony  Yes, the carousel. I expected to messages like the desktop. 

![screenshot_2016-09-16-20-14-27](https://cloud.githubusercontent.com/assets/4212119/18594822/7d2d315c-7c4a-11e6-8a16-20f0127d7f41.png)

**Comment by PadawanTony** [comment]
@rdok Yeah, I guess this is the way this template is designed. It wouls be nice to have the titles but I cannot imagine where to put them to show nicely. (Same goes for #20 )

**Comment by rdok** [comment]
@PadawanTony OK (neither do I lol), I'm closing this task and #20. OK?

**Comment by PadawanTony** [comment]
ok :)
