### ISSUE TITLE
Change project's name camel case to using dashes.

### ISSUE THREAD

**Issue by rdok** [codeburrow/company-web-app#2]
**TODO:** Change CompanyWebApp to company-web-app.  
**Why:** Check all popular GitHub projects. They all follow this conventions.  
**Additional info:** If you are wondering why, this has to do with search engines. Search engines find it easier to index urls that are connected with dashes '-' instead of either camel cases, or even underscores.

**Comment by PadawanTony** [comment]
Done. Later tonight I will also change the name on the server and close this issue.

**Comment by PadawanTony** [comment]
Change project name in server as well.

It might be helpful for future references to note that I had to change the Document Root under /etc/apache2/sites-enabled/000-default.conf
