### ISSUE TITLE
Add environment variables for database. 

### ISSUE THREAD

**Issue by rdok** [codeburrow/company-web-app#23]
@PadawanTony Do you mind if I add environment variables for the database? I need this when developing locally.

**Comment by PadawanTony** [comment]
@rdok Sure go ahead. Maybe use `.env`?

(Although there is no db. Just for the blog we have one.)

**Comment by rdok** [comment]
Resolved by #24  & [.env](https://github.com/rdok/company-web-app/blob/55b8f41444ef40fae08f3cb3a0b47edd6f06cf97/.env.example)
