### ISSUE TITLE
Display Posts in a nice manner

### ISSUE THREAD

**Issue by PadawanTony** [codeburrow/company-web-app#6]
Right now the whole post is one big paragraph.

How can we make it so that it display the spacing (ex: new lines) and the format (ex: lists) correctly?

---

Maybe we should make it so that (when we have the admin panel and the user writes in the textarea) the textarea understands automatically what to do? For example, when I press 'enter' it know to create a new paragraph? (exactly this editor right here?)

**Comment by rdok** [comment]
@PadawanTony The solution you suggest is valid--the one I thought about is https://mindmup.github.io/bootstrap-wysiwyg/ 

I'm not sure to which post you are referring to.

**Comment by PadawanTony** [comment]
Thx @rdok, I will take a look at it.

I was referring to http://www.codeburrow.com/blog

**Comment by PadawanTony** [comment]
1) https://www.tinymce.com/
2) https://www.youtube.com/watch?v=XtPgzs9PLCk

**Comment by PadawanTony** [comment]
Configure tinymce so that it displays even prettier

**Comment by PadawanTony** [comment]
https://github.com/codeburrow/company-web-app/commit/b73b07d81edf63dc260acbd36f337e4ac73df9af
